### ISSUE TITLE
Conflict with NTFS Tool on macOS: disks cannot be identified after using NTFS Tool

### ISSUE THREAD

**Issue by jsmjsm** [nielsmouthaan/ejectify-macos#1]
Great app! 
But I think there's a little bug is that when I mount my NTFS format hard disk then use the NTFS tool(to make my NTFS disk can be read and written on macOS). 
Then, the Ejectify can not identify the NTFS disk, naturally, I cannot eject the NTFS disk with Ejectify.
BUT, when I turn off the NTFS tool, the Ejectify work as expected.

maybe there're bugs on how Ejectify identify / filter disks.

**Comment by jsmjsm** [comment]
The following is my guess to how the conflict be occurred:
I have read the source code and I think the bug maybe located at the `isVolumeURL(_ url: URL) -> Bool{}` function (`# Line 70 Volume.swift`)
the code 
```swift
url.pathComponents[VolumeComponent.root.rawValue] == VolumeReservedNames.Volumes.rawValue
```

The NTFS tool **might** change the `url/value/other value ...` of the disks, which are filtered out by the `isVolumeURL()` function. In this case, the conflict is occurred.

**Comment by nielsmouthaan** [comment]
Thanks for reporting this. I expect the same happens. What's the actual path of the NTFS volume (after starting the NTFS tool)?

**Comment by nielsmouthaan** [comment]
Closing this issue as it's outdated.
