### ISSUE TITLE
Possible issue with Mac OS Big Sur

### ISSUE THREAD

**Issue by garyshell** [nielsmouthaan/ejectify-macos#12]
I recently upgraded to Big Sur and occasionally ejectify is not ejecting my external hard drive when the MacBookPro goes to sleep.  At my office the MacBook lives in an upright holder and is attached to a USB-C dock where my TimeMachine drive is plugged in.  I put the MacBook to sleep and disconnect the dock each night to take the MacBook home.  Normally the next day when I plug things back in, there is no warning.  Since the Big Sur upgrade I am occasionally (not every day) seeing the dreaded "DISK NOT EJECTED PROPERLY" notification.

**Comment by nielsmouthaan** [comment]
Have you tried switching to another "Unmount when" mode, e.g. "Screen is locked"? That option appears to work better in my case.

**Comment by alpsoy** [comment]
Same issue here. I've just downloaded the app, but it seems it does not work when I put my MBP to sleep. It works when I lock it as @nielsmouthaan suggested tough, but I would expect it to work for sleeping too as it was the main reason why I started using the app. I am on macOS 11.1.

**Comment by nielsmouthaan** [comment]
@alpsoy How are you putting your MacBook to sleep? And does setting "Unmount when" to "Screen is locked" fully solve your issue? Like I said, this option works better for me too as my screen (that has my drive connected) powers off automatically when macOS instructs my screens to start sleeping. Hence, "System starts sleeping" is too late already.

**Comment by garyshell** [comment]
My drive is connected directly to my MacBook Pro via a USB-C cable. I have not tired the "screen is locked" option. The app worked fine until I upgraded to Big Sur, and as I initially said this issue is only occasionally happening.  Most of the time when I put the machine to sleep, disconnect the MacBook and then take it home and the following day reconnect the drive back at the office and then wake the laptop I see no warning about the disk not being ejected. But once in a while I am seeing that error.  Prior to Big Sur I never saw the error after installing ejectify.

**Comment by alpsoy** [comment]
> @alpsoy How are you putting your MacBook to sleep? And does setting "Unmount when" to "Screen is locked" fully solve your issue? Like I said, this option works better for me too as my screen (that has my drive connected) powers off automatically when macOS instructs my screens to start sleeping. Hence, "System starts sleeping" is too late already.

I put it to sleep via Alfred, so it is system command. Actually my external screen never turns off completely, so the external drive has power all the time. I just want it unmounted to prevent from sudden power outages which happens frequently during night time.

**Comment by nielsmouthaan** [comment]
> I put it to sleep via Alfred, so it is system command. Actually my external screen never turns off completely, so the external drive has power all the time. I just want it unmounted to prevent from sudden power outages which happens frequently during night time.

And does it not work at all in your case, or just randomly? In the case of the latter, is there anything you feel could be related?

**Comment by alpsoy** [comment]
> > I put it to sleep via Alfred, so it is system command. Actually my external screen never turns off completely, so the external drive has power all the time. I just want it unmounted to prevent from sudden power outages which happens frequently during night time.
> 
> And does it not work at all in your case, or just randomly? In the case of the latter, is there anything you feel could be related?

I have made several try outs with different scenarios, like manually ejecting the disk for the night. The problem seems like some kind of weird combination of macOS & my display's power on behaviour, which together mount the disk back. So cannot make sure if there is anything related directly with Ejectify. Thank you for help.

**Comment by nielsmouthaan** [comment]
The upcoming version will support multi-selecting "Unmount when" options. Perhaps this could solve your issue?

**Comment by bradycline** [comment]
Not sure if it's the same issue, but I purchased Ejectify, left at default settings and the very first time I let it sleep, I was greeted by this when I opened the lid. This is the type of problem I was trying to avoid by getting Ejectify. Luckily, the drive was still readable. I just got the new version and I'll try some of the options.
![Screen Shot 2021-04-25 at 2 16 15 PM](https://user-images.githubusercontent.com/27686869/116034655-3b972b00-a696-11eb-8a72-4eb954aabc64.png)
Big Sur. M1 MacBook Pro. SanDisk Extreme SSD connected by USB-C.

**Comment by nielsmouthaan** [comment]
That's odd. Ejectify only tries to unmount the volumes (safely, unless you enabled _Force unmount_) when it detects your system starts sleeping (depending how you configured _Unmount when_). This might be a volume issue. I would recommend you to verify and repair it via Disk Utility.

**Comment by nielsmouthaan** [comment]
> > That's odd. Ejectify only tries to unmount the volumes (safely, unless you enabled _Force unmount_) when it detects your system starts sleeping (depending how you configured _Unmount when_). This might be a volume issue. I would recommend you to verify and repair it via Disk Utility.
> 
> I had the problem, that Ejectify only worked correct with "Force unmount" enabled (Mac Mini M1, USB-C-Hub, Lacie & Seagate SSD) .
> After repair of the SSDs via Disk Utility, Ejectify works correct **without** "Force unmount" enabled.
> 
> Now my question: do I understand it correctly than when I enable "Force unmount" it is not safe for the hard drives?

It might corrupt data, which could affect both the app using that data, or the volume entirely. It seems like an app is preventing the volume from getting unmounted properly. Can you take a look at this[ StackOverflow answer](https://apple.stackexchange.com/a/104850) and see if this helps finding the app that causes this?

**Comment by nielsmouthaan** [comment]
[This planned enhancement](https://github.com/nielsmouthaan/ejectify-macos/issues/40) is a possible solution to this issue. It will disable the notification entirely.
