### ISSUE TITLE
After closing lid (and sleep) on MacBook Pro, Ejectify does not mount sd-volumes automatically

### ISSUE THREAD

**Issue by jaolie** [nielsmouthaan/ejectify-macos#2]
Hi, I have Ejectify, and it works fine when closing the MacBook Pro lid (2019), or when using "Sluimer" in the Apple menu.
After "Sluimer" the volumes are mounted. 
But when I close the laptop lid, and open it again, these volumes (both SD-cards are on an Anker-hub).

**Comment by nielsmouthaan** [comment]
Thanks for reporting this. So if I understand correctly:

✔️ Ejectify properly unmounts volumes when clicking "Sluimer" and mounts them again after you wake up your Mac.
❌ Ejectify properly unmounts volumes when closing the lid but does not mount them properly again?

If this is the case it sounds like Ejectify tries mounting the volumes while they are not available yet. Have you tried connecting the SD card (reader) directly on your Mac (if possible)?

Also can you try updating the "Unmount when..." option to "Screens started sleeping"?

**Comment by jaolie** [comment]
Ho Niels, thanks for your message!
I will try your suggestions. In the mean time I will have been using the app for a longer time, so I will have more data as for it’s effectiveness.  (The trend for now is: it mostly works, but sometimes it doesn’t).

Best,
Johan Olie

Verstuurd vanaf mijn iPad

**Comment by nielsmouthaan** [comment]
Keep me posted 👍

**Comment by nielsmouthaan** [comment]
Added a [feature request](https://github.com/nielsmouthaan/ejectify-macos/issues/18) that potentially solves this issue. Closing for now.
