### ISSUE TITLE
Eject external disks at restart and shutdown

### ISSUE THREAD

**Issue by vangquan** [nielsmouthaan/ejectify-macos#26]
Can you add the trigger to unmount disks at restart or shutdown?
Thank you.

**Comment by nielsmouthaan** [comment]
It doesn't, as ejecting is something that's part of the default workflow when shutting down your Mac. Hence, it shouldn't be needed. Why are you asking?

**Comment by nielsmouthaan** [comment]
Closing as this functionality is considered out-of-scope for Ejectify. The operating system should handle unmounting volumes when the system shuts down.
