### ISSUE TITLE
Use Ejectify with SD-Cards in the internal card reader

### ISSUE THREAD

**Issue by bohning** [nielsmouthaan/ejectify-macos#29]
I’m having the target problem with my SD card that permanently sits in my Mac card reader slot. However, after installing Ejectify, I only see "No Volumes", so it seems that it only works for drives connected via USB? If so, it would be a helpful addition (at least for me), if Ejectify also worked for SD cards in the card slot.

**Comment by nielsmouthaan** [comment]
Likely because it's seen as an internal drive. Can you send me an email so I can provide you an earlier version that doesn't have this "limitation"? You can contact me via the contact form on [ejectify.app](ejectify.app).

**Comment by bohning** [comment]
Thanks for getting back to me on this. Unfortunately, the link ejectify.app to contact you does not work for me (HTTP ERROR 406).

**Comment by nielsmouthaan** [comment]
nielsmouthaan _at_ me.com

**Comment by nielsmouthaan** [comment]
Duplicate of this [planned enhancement ticket](https://github.com/nielsmouthaan/ejectify-macos/issues/36).
