### ISSUE TITLE
Downloaded. Doesn't open

### ISSUE THREAD

**Issue by hbankstoo** [nielsmouthaan/ejectify-macos#35]
I'd like to start using this, but it doesn't open. I moved it into the Applications folder.

What else do I need to do?

**Comment by nielsmouthaan** [comment]
Ejectify doesn't have a window, it only runs from the status bar. Do you see its icon there (next to your clock, WiFi icon, etc.)?

**Comment by hbankstoo** [comment]
Gotcha. Now I see it. How to configure so drive unmounts at sleep, remounts after wakening?

**Comment by hbankstoo** [comment]
See the "Unmount when… system starts sleeping". Yay.

Do I need to do anything with mount after delay? Or will it just mount immediately upon wakening?

**Comment by nielsmouthaan** [comment]
You don't have to change that setting. It's only in case you have some issues with Ejectify.

**Comment by hbankstoo** [comment]
Hi,

I use TimeMachineEditor to schedule a daily backup, rather than the
default hourly ones.  Every second day, it doesn't seem to work, and I have
to do it manually. Is there a workaround

Also, are you able to post to <
https://developer.apple.com/forums/thread/679836?page=3> about the dreaded
message Disk Not Ejected Properly?

I've been trying to comment about your app but am prohibited from posting
[not an Apple Developer]

Thanks again,

Hannah Banks
617.877.7885 cell
617.236.1876
facebook.com/HannahBankstoo
