### ISSUE TITLE
Add support for internal volumes (SD cards, images, etc.)

### ISSUE THREAD

**Issue by nielsmouthaan** [nielsmouthaan/ejectify-macos#36]
The latest version of Ejectify disabled internal volumes. Since SD cards are considered internal by the operating system, Ejectify doesn't support automatically (un)mounting them. This should be reverted.

**Comment by mattthw** [comment]
I bought this specifically for SD Cards. I feel like this should be called out as a limitation before customers on the readme before customers purchase the app?

**Comment by nielsmouthaan** [comment]
Send me an email, and I'll send you a version that supports SD cards.

**Comment by EhongLi** [comment]
whats your email?

**Comment by nielsmouthaan** [comment]
nielsmouthaan at me.com

**Comment by nielsmouthaan** [comment]
Ejectift 1.2.2 now supports internal but ejectable volumes like SD cards.
