### ISSUE TITLE
Manually unmount all volumes

### ISSUE THREAD

**Issue by bhaveshcp** [nielsmouthaan/ejectify-macos#39]
Request an enhancement to:
1. Disable auto-unmounting
and
2. Have an option to manually unmount all checked volumes.

This is to simplify moving a laptop from "Desktop" mode with external drives on a hub, to portable use.

**Comment by nielsmouthaan** [comment]
While cleaning up existing issues and planning version 2.0 I bumped into this one and realized the requested functionality already exists. You can (un)check a volume from Ejectify's menu to toggle whether it should be automatically (un)mounted. The option _Unmount all_ manually unmounts all checked volumes.
