### ISSUE TITLE
Request + offer: localisation files for translating

### ISSUE THREAD

**Issue by iAmRenzo** [nielsmouthaan/ejectify-macos#4]
It would be nice if you had separate language files for localisation/translation. I would offer to translate to Dutch, but when I look at your name I think you are Dutch yourself 😉
However: I'd like to help out if I can.

**Comment by nielsmouthaan** [comment]
Thanks for the offer! Dutch indeed but I also got someone else willing to translate to Spanish so might do this in the future.

**Comment by nielsmouthaan** [comment]
Dutch translations implemented in 1.1.0.
