### ISSUE TITLE
Compatibility with Ventura

### ISSUE THREAD

**Issue by rtiainen** [nielsmouthaan/ejectify-macos#43]
Ejectify does not seem to function correctly with Ventura Public Beta 3.

Configuration: Mac Studio M1 Max with a display that has a USB hub that power downs whenever display powers down. Regardless of the settings the Ejectify fails to unmount the external drives connected to the display's USB hub before the display powers down. Sometimes after wake up there is dozens of notifications, that seem to imply that there has been a burst of mounts and dirty unmounts. Manual unmounting from Ejectify menu bar (Unmount all) works perfectly.

Ejectify worked in this system before upgrade to Ventura Beta which seems to imply that something has changed with Ventura or current beta is buggy.

**Comment by nielsmouthaan** [comment]
Thanks. I'll look into this.

**Comment by nielsmouthaan** [comment]
I've tested on Ventura (beta 4) and Ejectify seems to work fine here. Did you update Ventura to beta 4 or 5 and check if that solved your issue?

**Comment by nielsmouthaan** [comment]
Closing this issue as it has been old and Ejectify seems to work fine on Ventura.
