### ISSUE TITLE
Check Mount Point of Drive

### ISSUE THREAD

**Issue by ekwipt** [nielsmouthaan/ejectify-macos#44]
I've been getting this issue when I've ejected my Thunderbolt drive, the mac has gone to sleep, and when I wake it back up it mounts the drive but changes the mount point.

for example, thunderbolt drive was called /Volumes/External_1

when remounted it gets the name /Volumes/External_1 2

Is there a way to check if drives have been ejected properly and unmounted in volumes?

**Comment by nielsmouthaan** [comment]
Hmm, that's something the operating system does. Not sure why, perhaps the previous mount point is unavailable? You can check the [Console app](https://support.apple.com/guide/console/cnsl1012/mac) for events related to (un)mounting.

**Comment by ekwipt** [comment]
yes it's because it doesn't unmount properly, so in the /Volumes there's still a mount point called External_1, so it gives it a prefix of External_1 2

**Comment by nielsmouthaan** [comment]
Can you temporarily check the _Force unmount_ option to check if that makes a difference?

**Comment by nielsmouthaan** [comment]
Closing issue as this issue is "caused" by the operating system.
