### ISSUE TITLE
link is dead, where to download Ejectify?

### ISSUE THREAD

**Issue by mvsilfho** [nielsmouthaan/ejectify-macos#48]
You can access earlier made purchases via Gumroad. Refer to [this article](https://customers.gumroad.com/article/199-how-do-i-access-my-purchase) for more information. Hence, there is no need to purchase Ejectify again. 

The link to the article is dead, so I'm unable to download Ejectify :-(

Regards,
Mark

**Comment by nielsmouthaan** [comment]
Please use [this link](https://customers.gumroad.com/accessing-your-purchase/how-do-i-access-my-purchase) instead.
