### ISSUE TITLE
Don't show Ejectify running in Activity Monitor after reboot??

### ISSUE THREAD

**Issue by DavGMac** [nielsmouthaan/ejectify-macos#54]
I might be doing something wrong, but I downloaded ejectify and unzipped it and moved the application to the applications folder and ran it .... I rebooted and when I came back up, was not in application folder anymore or running in Activity Monitor. When I did get it to run before rebooting, where do you find the options and drop-down menu etc ... I opened finder and looked all through the menu bar and didnt see anything like was mentioned. Please help me figure this out?  LOL 

Thanks, 

Davie M.

**Comment by nielsmouthaan** [comment]
That's odd. You should copy Ejectiy into your Applications folder and run it from there. An eject icon in the menu bar near your clock should contain all the options. There's no other UI.

**Comment by DavGMac** [comment]
Ok, I got it working now. Thanks!!David McIntoshEmail: ***@***.***: (918) 798-3283On Jan 15, 2023, at 6:56 AM, Niels Mouthaan ***@***.***> wrote:﻿
That's odd. You should copy Ejectiy into your Applications folder and run it from there. An eject icon in the menu bar near your clock should contain all the options. There's no other UI.

**Comment by nielsmouthaan** [comment]
Great!
