### ISSUE TITLE
DMG files are automatically selected to mount/umount

### ISSUE THREAD

**Issue by iAmRenzo** [nielsmouthaan/ejectify-macos#6]
I noticed that DMG files that are mounted also are enabled for mount/unmount.
It would be nice to have preferences to enable/disable certain types of mounted drives.

**Comment by nielsmouthaan** [comment]
Good point! Tested this myself and this is something that indeed could be improved.

**Comment by iAmRenzo** [comment]
I thought so. No rush, just posting things I see or notice ;)

**Comment by nielsmouthaan** [comment]
Implemented in 1.1.0.
