### ISSUE TITLE
No eject icon in the status bar

### ISSUE THREAD

**Issue by loqzer** [nielsmouthaan/ejectify-macos#63]
I downloaded the app and copied it to applications. After starting it, no eject icon appears in the status bar. Even after re-mounting my external harddrive I don't get an icon at all.

I'm on Sonoma 14.1.2 (23B92), Apple MacBook Pro M2

**Comment by nielsmouthaan** [comment]
Can you double-check you're running it from the applications folder? If it is, please check the Console app for clues why the app doesn't start.

**Comment by loqzer** [comment]
Found the following error in the logs:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Ejectify [13464]
Path:                  /private/var/folders/*/Ejectify.app/Contents/MacOS/Ejectify
Identifier:            Ejectify
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-12 15:47:48.6039 +0100
OS Version:            macOS 14.1.2 (23B92)
Report Version:        12
Anonymous UUID:        82C76856-1CE7-55C3-D1A5-7B217F02F579

Sleep/Wake UUID:       B7ED0F19-5C0C-4614-8C50-6AA6830423DB

Time Awake Since Boot: 35000 seconds
Time Since Wake:       2219 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_MEMORY_ERROR at 0x00000001000acdec
Exception Codes:       0x000000000000000a, 0x00000001000acdec

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [13464]

VM Region Info: 0x1000acdec is in 0x1000a8000-0x1000b8000;  bytes after start: 19948  bytes before end: 45587
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  mapped file                 1000a8000-1000b8000    [   64K] r-x/r-x SM=COW  ...t_id=9e7d252b
      mapped file                 1000b8000-1000bc000    [   16K] r--/rw- SM=COW  ...t_id=9be9142b

Kernel Triage:
VM - (arg = 0x0) Object has no pager


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	       0x1000acdec ???
1   CoreFoundation                	       0x18bf2a8ec ___CFXRegistrationPost_block_invoke + 88
2   CoreFoundation                	       0x18bf2a834 _CFXRegistrationPost + 440
3   CoreFoundation                	       0x18be6548c _CFXNotificationPost + 764
4   Foundation                    	       0x18cf57030 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
5   AppKit                        	       0x18f89b344 __postVolumeNotification_block_invoke + 64
6   CoreFoundation                	       0x18bea1894 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
7   CoreFoundation                	       0x18bea17a8 __CFRunLoopDoBlocks + 356
8   CoreFoundation                	       0x18bea0c3c __CFRunLoopRun + 2440
9   CoreFoundation                	       0x18be9fc5c CFRunLoopRunSpecific + 608
10  HIToolbox                     	       0x19641c448 RunCurrentEventLoopInMode + 292
11  HIToolbox                     	       0x19641c284 ReceiveNextEventCommon + 648
12  HIToolbox                     	       0x19641bfdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
13  AppKit                        	       0x18f67ac54 _DPSNextEvent + 660
14  AppKit                        	       0x18fe50ebc -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
15  AppKit                        	       0x18f66e100 -[NSApplication run] + 476
16  AppKit                        	       0x18f6453cc NSApplicationMain + 880
17  ???                           	       0x1000af49c ???
18  dyld                          	       0x18ba490e0 start + 2360

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x18bd848b4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18bd96d30 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18bd8d4f0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x18bd84c38 mach_msg + 24
4   CoreFoundation                	       0x18bea1ea4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18bea076c __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18be9fc5c CFRunLoopRunSpecific + 608
7   AppKit                        	       0x18f7a4404 _NSEventThread + 144
8   libsystem_pthread.dylib       	       0x18bdc5034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18bdbfe3c thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	       0x18bdbfe28 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18bdbfe28 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600003405200   x1: 0x00000001000b6120   x2: 0x00006000010180e0   x3: 0x0000600003405200
    x4: 0x00006000010180e0   x5: 0x0000000000041c00   x6: 0x0000000150604080   x7: 0x000000016fd55808
    x8: 0x00000001e241e900   x9: 0x00000001000b6120  x10: 0x000000015060c180  x11: 0x000000000000001f
   x12: 0x0000000000000000  x13: 0x0000000150606f40  x14: 0x04000001000bcff5  x15: 0x00000001000bcff0
   x16: 0x00000001000bcff0  x17: 0xd7068001000acdec  x18: 0x0000000000000000  x19: 0x00000001000b6120
   x20: 0x000000016fd55998  x21: 0x00006000010180e0  x22: 0x0000600003405200  x23: 0x0000600001035440
   x24: 0x0000000000000000  x25: 0x0000000000041c00  x26: 0x0000000000000000  x27: 0x0000000b0000000a
   x28: 0x000000016fd55878   fp: 0x000000016fd55810   lr: 0x000000018be96820
    sp: 0x000000016fd557d0   pc: 0x00000001000acdec cpsr: 0x60001400
   far: 0x00000001000acdec  esr: 0x82000007 (Instruction Abort) Translation fault

Binary Images:
       0x10049c000 -        0x1004a7fff libobjc-trampolines.dylib (*) <c9ce7923-2f2d-31eb-a6e4-0f3b7a78f895> /usr/lib/libobjc-trampolines.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18be24000 -        0x18c2fbfff com.apple.CoreFoundation (6.9) <9f046e36-7286-3a6e-a280-699d6e47cfaf> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x18cf4e000 -        0x18db9bfff com.apple.Foundation (6.9) <2126fd9a-52ce-3eb2-8640-b57535e073b8> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x18f641000 -        0x190955fff com.apple.AppKit (6.9) <b475e541-691d-39c6-8ca4-e414b0d3dd88> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1963ec000 -        0x1966abfff com.apple.HIToolbox (2.1.1) <4dffb7eb-bbcd-3ff6-a203-5a0b97358ee8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x18ba43000 -        0x18bad7317 dyld (*) <ec7a3ba0-f9bf-3ab8-a0f4-8622e5606b20> /usr/lib/dyld
       0x18bd83000 -        0x18bdbdfef libsystem_kernel.dylib (*) <b7751381-1442-30b5-91b9-ad7be461bebe> /usr/lib/system/libsystem_kernel.dylib
       0x18bdbe000 -        0x18bdcaff3 libsystem_pthread.dylib (*) <daf95373-5de6-39a1-a6ce-d87f3f0629cc> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          560K       26 
CoreAnimation                       16K        1 
CoreGraphics                        32K        2 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.2G       42 
MALLOC guard page                  192K       12 
STACK GUARD                       56.1M        4 
Stack                             9808K        4 
VM_ALLOCATE                         80K        5 
__AUTH                            1437K      252 
__AUTH_CONST                      23.2M      436 
__CTF                               824        1 
__DATA                            9951K      421 
__DATA_CONST                      21.1M      441 
__DATA_DIRTY                      1289K      138 
__FONT_DATA                          4K        1 
__LINKEDIT                       886.5M        2 
__OBJC_RO                         70.8M        1 
__OBJC_RW                         2156K        1 
__TEXT                           517.7M      459 
dyld private memory                272K        2 
mapped file                      162.3M       28 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              2.9G     2295 



-----------
Full Report
-----------

{"app_name":"Ejectify","timestamp":"2023-12-12 15:47:50.00 +0100","app_version":"","slice_uuid":"74171529-b241-3168-9c30-091362a6719e","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 14.1.2 (23B92)","roots_installed":0,"incident_id":"530E29E7-4189-446F-B7CE-CB929E3488DC","name":"Ejectify"}
{
  "uptime" : 35000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,9",
  "coalitionID" : 15011,
  "osVersion" : {
    "train" : "macOS 14.1.2",
    "build" : "23B92",
    "releaseType" : "User"
  },
  "captureTime" : "2023-12-12 15:47:48.6039 +0100",
  "codeSigningMonitor" : 1,
  "incident" : "530E29E7-4189-446F-B7CE-CB929E3488DC",
  "pid" : 13464,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-12-12 15:46:05.2917 +0100",
  "procStartAbsTime" : 852375202685,
  "procExitAbsTime" : 854854548937,
  "procName" : "Ejectify",
  "procPath" : "\/private\/var\/folders\/*\/Ejectify.app\/Contents\/MacOS\/Ejectify",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "nl.nielsmouthaan.Ejectify",
  "crashReporterKey" : "82C76856-1CE7-55C3-D1A5-7B217F02F579",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "wakeTime" : 2219,
  "sleepWakeUUID" : "B7ED0F19-5C0C-4614-8C50-6AA6830423DB",
  "sip" : "enabled",
  "vmRegionInfo" : "0x1000acdec is in 0x1000a8000-0x1000b8000;  bytes after start: 19948  bytes before end: 45587\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  mapped file                 1000a8000-1000b8000    [   64K] r-x\/r-x SM=COW  ...t_id=9e7d252b\n      mapped file                 1000b8000-1000bc000    [   16K] r--\/rw- SM=COW  ...t_id=9be9142b",
  "exception" : {"codes":"0x000000000000000a, 0x00000001000acdec","rawCodes":[10,4295675372],"type":"EXC_BAD_ACCESS","signal":"SIGBUS","subtype":"KERN_MEMORY_ERROR at 0x00000001000acdec"},
  "termination" : {"flags":0,"code":10,"namespace":"SIGNAL","indicator":"Bus error: 10","byProc":"exc handler","byPid":13464},
  "ktriageinfo" : "VM - (arg = 0x0) Object has no pager\n",
  "vmregioninfo" : "0x1000acdec is in 0x1000a8000-0x1000b8000;  bytes after start: 19948  bytes before end: 45587\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  mapped file                 1000a8000-1000b8000    [   64K] r-x\/r-x SM=COW  ...t_id=9e7d252b\n      mapped file                 1000b8000-1000bc000    [   16K] r--\/rw- SM=COW  ...t_id=9be9142b",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":485096,"threadState":{"x":[{"value":105553170813440},{"value":4295713056},{"value":105553133142240},{"value":105553170813440},{"value":105553133142240},{"value":269312},{"value":5643452544},{"value":6171219976},{"value":8090937600,"symbolLocation":0,"symbol":"kCFXNotificationPlaceholderObserver"},{"value":4295713056},{"value":5643485568},{"value":31},{"value":0},{"value":5643464512},{"value":288230380447453173},{"value":4295741424},{"value":4295741424},{"value":15494212309798800876},{"value":0},{"value":4295713056},{"value":6171220376},{"value":105553133142240},{"value":105553170813440},{"value":105553133261888},{"value":0},{"value":269312},{"value":0},{"value":47244640266},{"value":6171220088}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6642296864},"cpsr":{"value":1610617856},"fp":{"value":6171219984},"sp":{"value":6171219920},"esr":{"value":2181038087,"description":"(Instruction Abort) Translation fault"},"pc":{"value":4295675372,"matchesCrashFrame":1},"far":{"value":4295675372}},"queue":"com.apple.main-thread","frames":[{"imageOffset":4295675372,"imageIndex":1},{"imageOffset":1075436,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":88,"imageIndex":2},{"imageOffset":1075252,"symbol":"_CFXRegistrationPost","symbolLocation":440,"imageIndex":2},{"imageOffset":267404,"symbol":"_CFXNotificationPost","symbolLocation":764,"imageIndex":2},{"imageOffset":36912,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":88,"imageIndex":3},{"imageOffset":2466628,"symbol":"__postVolumeNotification_block_invoke","symbolLocation":64,"imageIndex":4},{"imageOffset":514196,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__","symbolLocation":28,"imageIndex":2},{"imageOffset":513960,"symbol":"__CFRunLoopDoBlocks","symbolLocation":356,"imageIndex":2},{"imageOffset":511036,"symbol":"__CFRunLoopRun","symbolLocation":2440,"imageIndex":2},{"imageOffset":506972,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":2},{"imageOffset":197704,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":5},{"imageOffset":197252,"symbol":"ReceiveNextEventCommon","symbolLocation":648,"imageIndex":5},{"imageOffset":196572,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":76,"imageIndex":5},{"imageOffset":236628,"symbol":"_DPSNextEvent","symbolLocation":660,"imageIndex":4},{"imageOffset":8453820,"symbol":"-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":716,"imageIndex":4},{"imageOffset":184576,"symbol":"-[NSApplication run]","symbolLocation":476,"imageIndex":4},{"imageOffset":17356,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":4},{"imageOffset":4295685276,"imageIndex":1},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":6}]},{"id":485184,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":163840117440512},{"value":0},{"value":163840117440512},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":38147},{"value":0},{"value":1},{"value":38147},{"value":469983},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8236957744},{"value":0},{"value":4294967295},{"value":2},{"value":163840117440512},{"value":0},{"value":163840117440512},{"value":6174072936},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6641249584},"cpsr":{"value":4096},"fp":{"value":6174072784},"sp":{"value":6174072704},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6641174708},"far":{"value":0}},"frames":[{"imageOffset":6324,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":7},{"imageOffset":81200,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":7},{"imageOffset":42224,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":7},{"imageOffset":7224,"symbol":"mach_msg","symbolLocation":24,"imageIndex":7},{"imageOffset":515748,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":2},{"imageOffset":509804,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":2},{"imageOffset":506972,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":2},{"imageOffset":1455108,"symbol":"_NSEventThread","symbolLocation":144,"imageIndex":4},{"imageOffset":28724,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":8},{"imageOffset":7740,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":487295,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6172930048},{"value":18459},{"value":6172393472},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6172930048},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6641417768},"far":{"value":0}}},{"id":488395,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6171783168},{"value":0},{"value":6171246592},{"value":0},{"value":278532},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6171783168},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":6641417768},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4299800576,
    "size" : 49152,
    "uuid" : "c9ce7923-2f2d-31eb-a6e4-0f3b7a78f895",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6641827840,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "9f046e36-7286-3a6e-a280-699d6e47cfaf",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2106"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6659825664,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 12902400,
    "uuid" : "2126fd9a-52ce-3eb2-8640-b57535e073b8",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "2106"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6700666880,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 20008960,
    "uuid" : "b475e541-691d-39c6-8ca4-e414b0d3dd88",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487.20.107"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6815662080,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 2883584,
    "uuid" : "4dffb7eb-bbcd-3ff6-a203-5a0b97358ee8",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6637760512,
    "size" : 607000,
    "uuid" : "ec7a3ba0-f9bf-3ab8-a0f4-8622e5606b20",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6641168384,
    "size" : 241648,
    "uuid" : "b7751381-1442-30b5-91b9-ad7be461bebe",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6641410048,
    "size" : 53236,
    "uuid" : "daf95373-5de6-39a1-a6ce-d87f3f0629cc",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6637010944,
  "size" : 4018896896,
  "uuid" : "6d1aeeac-d56f-3513-9ae1-3894fde828f3"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          560K       26 \nCoreAnimation                       16K        1 \nCoreGraphics                        32K        2 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.2G       42 \nMALLOC guard page                  192K       12 \nSTACK GUARD                       56.1M        4 \nStack                             9808K        4 \nVM_ALLOCATE                         80K        5 \n__AUTH                            1437K      252 \n__AUTH_CONST                      23.2M      436 \n__CTF                               824        1 \n__DATA                            9951K      421 \n__DATA_CONST                      21.1M      441 \n__DATA_DIRTY                      1289K      138 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       886.5M        2 \n__OBJC_RO                         70.8M        1 \n__OBJC_RW                         2156K        1 \n__TEXT                           517.7M      459 \ndyld private memory                272K        2 \nmapped file                      162.3M       28 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              2.9G     2295 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "2513118d18233716557b4bbecce2c2b90e155564",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63508950b3714d3622fc77f7",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "63508beab3714d3622fc7808"
      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by nielsmouthaan** [comment]
Interesting, this one's new to me. Does it crash immediately after you start the app?

**Comment by nielsmouthaan** [comment]
It crashes immediately at launch, but the app is so simple that it could only be the listing of volumes causing this. Can you provide information (like a screenshot) on how your volumes look? Also, can you try starting Ejectify without any external volumes connected, just to see what it does?

**Comment by loqzer** [comment]
<img width="245" alt="image" src="https://github.com/nielsmouthaan/ejectify-macos/assets/81560233/21dac4c5-a45c-49b7-af56-cf70cd3e8664">

I only have one external drive, app also not starting after I unmounted the drive.

**Comment by nielsmouthaan** [comment]
Really strange. Unfortunately, I don't have time currently to look into this further. What are the first characters of your email address so I can initiate a refund? Thanks for reporting this, though. I'll look into this when I have time.

**Comment by loqzer** [comment]
Not necessary, after a reboot it is now working. Thanks for your support!
