### ISSUE TITLE
no NTFS volumes visible in Ejectify 

### ISSUE THREAD

**Issue by antonriemersma** [nielsmouthaan/ejectify-macos#69]
I installed ejectify. It seems to work because the eject symbol is in the bar, but it can't find my disk (no volumes) although a samsung t7 ssd is connected. Its formatted in NTFS, using the program Tuxera Disk Manager Version 2023.1, working on Sonoma 14.2.1. Does anyone have an idea how to get the disk visible for ejectify? 
![Scherm­afbeelding 2024-02-24 om 22 40 32](https://github.com/nielsmouthaan/ejectify-macos/assets/161167814/533fbbdd-a60b-43fa-ae77-69a8ac9eb5d8)

**Comment by nielsmouthaan** [comment]
How is the SSD connected?

**Comment by antonriemersma** [comment]
its directly connected by usb - c. Could it be because it's formatted in NTFS? 
I have connected 2 other memory cards (mac os uitgebreid & exfat)and they are visible in the menu.
<img width="1427" alt="Scherm­afbeelding 2024-02-25 om 15 23 35" src="https://github.com/nielsmouthaan/ejectify-macos/assets/161167814/3be4d192-613b-433d-9c53-bc3750efe1eb">

**Comment by nielsmouthaan** [comment]
I think it is. They're likely software-initiated and/or non-physical volumes, and Ejectify's source code filters them out. Depending on whether you're able to do so, you could check out its source code and see if you change the filters to make it work. Unfortunately, I don't have the time right now.

**Comment by antonriemersma** [comment]
Problem solved. I formatted the ssd  disk in exfat. Now it's visible like in ejectify. Seems NTFS is the problem
<img width="825" alt="Scherm­afbeelding 2024-02-25 om 21 57 38" src="https://github.com/nielsmouthaan/ejectify-macos/assets/161167814/f036552c-3c60-47ff-9d16-718b57ae9ad9">

**Comment by nielsmouthaan** [comment]
Thanks for letting me know!
