### ISSUE TITLE
Gumroad wants to set up recurring payments on Paypal

### ISSUE THREAD

**Issue by dspitzer** [nielsmouthaan/ejectify-macos#70]
I'd love to pay for Ejectify but Gumroad wants me to authorize recurring payments instead of a one-time purchase.

**Comment by nielsmouthaan** [comment]
That's odd. Ejectify is configured as a one-time purchase, so it shouldn't ask you to authorize recurring payments. I just tried it myself, and it didn't. Can you share details (like a screenshot) where it does, so I can investigate further?

**Comment by dspitzer** [comment]
Here's the Paypal Page View (German):
<img width="543" alt="image" src="https://github.com/nielsmouthaan/ejectify-macos/assets/1596671/1c1338c7-cc69-49cf-9143-a27f2e2400ce">

... and with Firefox Auto-Translate:
<img width="553" alt="image" src="https://github.com/nielsmouthaan/ejectify-macos/assets/1596671/dbea6e0f-5c84-40fa-beea-59da353d5ae6">

It's not exactly recurring payments but it authorizes Gumroad to take whatever they want in the future ...

**Comment by dspitzer** [comment]
Just an FYI: I authorized it now and paid for Ejectify. I just don't like that Gumroad requires this and if you hadn't answered I probably would've just skipped it. I'll try to remove the authorization from Paypal again (at the moment I'm just getting an error from Paypal when trying to do so 😜)

**Comment by nielsmouthaan** [comment]
It's something from Paypal indeed.
