### ISSUE TITLE
Launch at Login not working

### ISSUE THREAD

**Issue by mleroux13** [nielsmouthaan/ejectify-macos#71]
I have the box checked however the app does not launch at log in. I have also tried manually adding it, the app picture doesn't appear when I do and it does not work either.

On another note, would you be as kind as to share your settings also? Do you use a USB-C hub?

**Comment by nielsmouthaan** [comment]
Did you copy the app to your Applications folder and run/configure it from there? If you did, please check the Console app for any information on why Ejectify failed to launch at launch.

When I still used Ejectify (not using a hub anymore, but used one implicitly as it was built into my LG external display), Ejectify worked best when _Unmount, when_ was set to _Display, turned off_. I recommend just trying a few options to see what works best for you. Also check the [FAQ](https://github.com/nielsmouthaan/ejectify-macos/blob/main/README.md#frequently-asked-questions) if you encounter some issues.

**Comment by mleroux13** [comment]
Thanks for the quick reply! I do have it in the application folder and did configure it from there. 

Do you have any suggestions on what I could search for in console to find helpful info? I've never gotten an error notification, I do always have to manually open it though

**Comment by mleroux13** [comment]
Decided to delete and reinstall, now it does show the icon. Before it didn't when I tried to manually add it. I'll update in a few days, maybe it's good now!

![CleanShot 2024-03-29 at 08 35 01](https://github.com/nielsmouthaan/ejectify-macos/assets/165225572/bb6c364a-851b-4824-910a-adb6f2785871)

**Comment by nielsmouthaan** [comment]
Great!
